Report review
losDukos/DesApp-Grupo-C-012021-backend pull request #8
Opened 2021-06-05 22:00 UTC by pache0015

2021-06-05 22:13 UTC, w-etc requested changes
Está bueno pero me gustaría que revisemos unas cosas antes de mergearlo.

2021-06-05 22:13 UTC, w-etc commented on src/main/java/ar/edu/unq/desapp/grupoC/backenddesappapi/controller/ReviewController.java
> +        return reviewService.updateReview(review);
La única responsabilidad del Controller tiene que ser comunicarse con el Service para que haga todo. Lo que hiciste acá tiene que estar en el Service

2021-06-05 22:13 UTC, w-etc commented on src/main/java/ar/edu/unq/desapp/grupoC/backenddesappapi/model/Review.java
> +                  String location, Boolean isPremium, Boolean isReported) {
Sería raro que una Review recién creada ya esté reportada

2021-06-05 22:13 UTC, w-etc commented on src/main/java/ar/edu/unq/desapp/grupoC/backenddesappapi/model/Review.java
> +    Boolean isReported = false;
La desventaja que le veo a un booleano es que no hay forma de saber cuánta gente reportó una Review. A lo que a este modelo respecta, una Review reportada por 1 usuario y una Review reportada por 100 son igual de malas, lo que no está tan piola

2021-06-05 22:13 UTC, w-etc commented on src/main/java/ar/edu/unq/desapp/grupoC/backenddesappapi/controller/ReviewController.java
> +    @GetMapping("/id/unreportereds/{id}")
Acá hay dos problemas:

1. El primer "id" no es una Path Variable, por lo que tendrías que escribir id una y otra vez en vez de tener algo parametrizable.
2. Unreportereds no es una palabra. El término que estás buscando es "unreported". De paso, los adjetivos en inglés no se pluralizan.

2021-06-05 22:13 UTC, w-etc commented on src/main/java/ar/edu/unq/desapp/grupoC/backenddesappapi/controller/ReviewController.java
> +
Hasta donde me acuerdo este endpoint no estaba en las especificaciones. Pero si igual te interesa tener una manera de comprobar que una Review fue reportada correctamente, podemos agregar un nuevo filtro en getReviewsByTitleId

2021-06-05 22:13 UTC, w-etc commented on src/main/java/ar/edu/unq/desapp/grupoC/backenddesappapi/controller/ReviewController.java
> +        Specification<Review> specs = Specification.where(new ReviewByTitleId(id))
Tenés que acordarte de revisar que tengas la última versión del código antes de empezar a trabajar en algo nuevo. Había un PR en revisión con un refactor a la forma en la que funcionan los filtros. Ese refactor dejó obsoletas a las Specifications. Es probable que te comas un conflicto ahora, asi que cualquier cosa avisame.

2021-06-05 22:19 UTC, pache0015 commented on src/main/java/ar/edu/unq/desapp/grupoC/backenddesappapi/model/Review.java
> +    Boolean isReported = false;
Por eso el "TODO".

2021-06-08 19:58 UTC, w-etc approved these changes

2021-06-08 20:00 UTC, merged